-- Seed the canonical identity layer required by the normalized `bm` schema.
-- This intentionally does not depend on `public.players` from `mdef`.

select bm.ensure_player(canonical_name)
from (
  values
    ('Adam'),
    ('Agha'),
    ('Akid'),
    ('Anas'),
    ('Andhika'),
    ('Andri'),
    ('Angel'),
    ('Ari'),
    ('Aria'),
    ('Arin'),
    ('Azzam'),
    ('Boby'),
    ('Bowo'),
    ('Cahaya'),
    ('Dendi'),
    ('Dian'),
    ('Didick'),
    ('Dimas'),
    ('Dwi'),
    ('Ega'),
    ('Euis'),
    ('Fachri'),
    ('Fahmi'),
    ('Faiz'),
    ('Fakhri'),
    ('Febri'),
    ('Feri'),
    ('Fiya'),
    ('Fredi'),
    ('Ginanjar'),
    ('Hafian'),
    ('Hafidh'),
    ('Hidayah'),
    ('Hidayat'),
    ('Indah'),
    ('Ismet'),
    ('Jeki'),
    ('Jihan'),
    ('Kahfi'),
    ('Lita'),
    ('Lulud'),
    ('Mamski'),
    ('Maul'),
    ('Mr. Hong'),
    ('Naufal'),
    ('Nindya'),
    ('Nisa'),
    ('Nitho'),
    ('Novian'),
    ('Radita'),
    ('Rafi'),
    ('Raihan'),
    ('Raka'),
    ('Rakha'),
    ('Rama'),
    ('Randra'),
    ('Reggi'),
    ('Rifki'),
    ('Rizky'),
    ('Rudi'),
    ('Shania'),
    ('Silvi'),
    ('Suryadi'),
    ('Tari'),
    ('Tin'),
    ('Tommy'),
    ('Via'),
    ('Vieri'),
    ('Vina'),
    ('Visi'),
    ('Wahyu'),
    ('Zaid'),
    ('Zainal')
) as canonicals(canonical_name);

select bm.register_player_alias(alias_name, canonical_name)
from (
  values
    ('Agh', 'Agha'),
    ('Anjed', 'Andri'),
    ('Ari (Tmn Dimas)', 'Ari'),
    ('Bagas', 'Bowo'),
    ('Bobby', 'Boby'),
    ('Damm', 'Adam'),
    ('Dayat', 'Hidayat'),
    ('Dhika', 'Andhika'),
    ('Dika', 'Andhika'),
    ('Didik', 'Didick'),
    ('Dms', 'Dimas'),
    ('Feri (Tmn Novian)', 'Feri'),
    ('Hapid', 'Hafidh'),
    ('Iky', 'Rizky'),
    ('Jeki (Temen Anas)', 'Jeki'),
    ('Jihan Angkle', 'Jihan'),
    ('lud', 'Lulud'),
    ('Mr. Rama Udin', 'Rama'),
    ('Nindy', 'Nindya'),
    ('Pak hong', 'Mr. Hong'),
    ('Pina', 'Vina'),
    ('Randra (Temen Anas)', 'Randra'),
    ('Shan', 'Shania'),
    ('silvi (Tmn Agha)', 'Silvi'),
    ('Surya', 'Suryadi')
) as aliases(alias_name, canonical_name);
